
#Create a pandas DataFrame using the employee data

In [24]:
import pandas as pd
# create DataFrame:
data={
    "EmployeeID":[201,202,203,204,205,206,207,208,209,210],
    "Name":['Sarah','Michael','Jennifer','David','Lisa','James','Emma','Robert','Sophia','William'],
    "Department":['Enginnering','Sales','Marketing','Enginnering','HR','Sales','Enginnering','Marketing','Sales','HR'],
    "Salary":[85000,62000,71000,92000,58000,68000,78000,75000,65000,60000],
    "Performance Score":[4,3,5,5,4,4,3,4,5,3],
    "Years of Service":[5,3,7,8,4,6,2,5,4,3]
}
employees_data=pd.DataFrame(data)
employees_data

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Enginnering,85000,4,5
1,202,Michael,Sales,62000,3,3
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Enginnering,92000,5,8
4,205,Lisa,HR,58000,4,4
5,206,James,Sales,68000,4,6
6,207,Emma,Enginnering,78000,3,2
7,208,Robert,Marketing,75000,4,5
8,209,Sophia,Sales,65000,5,4
9,210,William,HR,60000,3,3

#Select and display only the Name, Department, and Salary columns from the employee DataFrame.

In [25]:
employees_data[['Name','Department','Salary']]

       Name   Department  Salary
0     Sarah  Enginnering   85000
1   Michael        Sales   62000
2  Jennifer    Marketing   71000
3     David  Enginnering   92000
4      Lisa           HR   58000
5     James        Sales   68000
6      Emma  Enginnering   78000
7    Robert    Marketing   75000
8    Sophia        Sales   65000
9   William           HR   60000

#Use iloc to retrieve and display the employee located at row position 5 (zero-based indexing)

In [26]:
employees_data.iloc[5]

EmployeeID             206
Name                 James
Department           Sales
Salary               68000
Performance Score        4
Years of Service         6
Name: 5, dtype: object

#Use loc to retrieve and display the employee whose EmployeeID is 208

In [27]:
employees_data.set_index('EmployeeID').loc[208]

Name                    Robert
Department           Marketing
Salary                   75000
Performance Score            4
Years of Service             5
Name: 208, dtype: object

#Filter the DataFrame to display only employees who work in the Engineering department

In [28]:
employees_data[employees_data['Department']=='Enginnering']

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
0         201  Sarah  Enginnering   85000                  4                 5
3         204  David  Enginnering   92000                  5                 8
6         207   Emma  Enginnering   78000                  3                 2

#Filter the DataFrame to show employees with a salary greater than 70,000

In [29]:
employees_data[employees_data['Salary']>70000]

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Enginnering,85000,4,5
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Enginnering,92000,5,8
6,207,Emma,Enginnering,78000,3,2
7,208,Robert,Marketing,75000,4,5

Filter employees from the Sales department who have a performance score of 4 or higher

In [30]:
employees_data[
    (employees_data['Department']=='Sales')&
    (employees_data['Performance Score']>=4)
]

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
5         206   James      Sales   68000                  4                 6
8         209  Sophia      Sales   65000                  5                 4

#Sort the DataFrame by salary in descending order and display the top three highest-paid employees

In [31]:
employees_data.sort_values('Salary',ascending=False).head(3)

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
3         204  David  Enginnering   92000                  5                 8
0         201  Sarah  Enginnering   85000                  4                 5
6         207   Emma  Enginnering   78000                  3                 2

#Sort the DataFrame by department in ascending order and by salary in descending order within each department

In [32]:
employees_data.sort_values(['Department','Salary'],ascending=[True,False])

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
3,204,David,Enginnering,92000,5,8
0,201,Sarah,Enginnering,85000,4,5
6,207,Emma,Enginnering,78000,3,2
9,210,William,HR,60000,3,3
4,205,Lisa,HR,58000,4,4
7,208,Robert,Marketing,75000,4,5
2,203,Jennifer,Marketing,71000,5,7
5,206,James,Sales,68000,4,6
8,209,Sophia,Sales,65000,5,4
1,202,Michael,Sales,62000,3,3